[
  { id: "P1", translation: "Dove È IL bagno?" },
  { id: "P2", translation: "Ciao, Come stai?" },
  { id: "P3", translation: "Ciao, Buongiorno" },
  { id: "P4", translation: "bene, E Voi?" },
  { id: "P5", translation: "Scusami, Dove È IL bagno? Grazie." },
  { id: "P6", translation: "menù, Per favore" },
  { id: "P7", translation: "conto, Per favore" },
  { id: "P8", translation: "Ho bisogno acqua, Per favore" },
  { id: "P9", translation: "Scusami, Ho bisogno un menù Per favore" },
  { id: "P10", translation: "Che cosa Voi consiglio?" },
  { id: "P11", translation: "saluti! buon appetito" },
  { id: "P12", translation: "Quanto È Questo?" },
  { id: "P13", translation: "Quanto Questo costo?" },
  { id: "P14", translation: "Scusami, Quanto È Questo?" },
  { id: "P15", translation: "SÌ, Per favore" },
  { id: "P16", translation: "NO, Grazie" },
  { id: "P17", translation: "Che cosa tempo Sei aprire?" },
  { id: "P18", translation: "Dove È IL Uscita?" },
  { id: "P19", translation: "Dove È IL Entrata?" },
  { id: "P20", translation: "Scusami, Dove È IL stazione autobus?" },
  { id: "P21", translation: "Ho bisogno un Taxi" },
  { id: "P22", translation: "Dove È IL autobus centro?" },
  { id: "P23", translation: "con formaggio" },
  { id: "P24", translation: "senza pollo" },
  { id: "P25", translation: "due grande pollo" },
  { id: "P26", translation: "uno piccolo formaggio" },
  { id: "P27", translation: "tre grande bevande" },
  { id: "P28", translation: "uno birra, Per favore" },
  { id: "P29", translation: "due piccolo pescare, Per favore" },
  { id: "P30", translation: "uno con maiale uno senza formaggio" },
  { id: "P31", translation: "due piccolo manzo" },
  { id: "P32", translation: "Voi parlare Inglese?" },
  { id: "P33", translation: "SÌ, Prego" },
  { id: "P36", translation: "Ciao, Buongiorno" },
  { id: "P37", translation: "Buongiorno, Come stai?" },
  { id: "P38", translation: "Buona notte E arrivederci" },
  { id: "P39", translation: "modifica, Per favore" },
  { id: "P40", translation: "ricevuta, Per favore" },
  { id: "P41", translation: "Quanto questo costo?" },
  { id: "P42", translation: "Quanto per Tutto?" },
  { id: "P43", translation: "Che cosa tempo è?" },
  { id: "P44", translation: "Che cosa tempo Sei aprire?" },
  { id: "P45", translation: "Quanto tempo?" },
  { id: "P46", translation: "uno biglietto treno, Per favore" },
  { id: "P47", translation: "Che cosa tempo Sei Chiuso?" },
  { id: "P48", translation: "Che cosa tempo È IL Prossimo autobus?" },
  { id: "P49", translation: "uno ora venti minuto" },
  { id: "P50", translation: "andiamo IL autobus È Qui" },
  { id: "P51", translation: "con formaggio" },
  { id: "P52", translation: "senza pollo" },
  { id: "P53", translation: "un po' speziato" },
  { id: "P54", translation: "senza carne" },
  { id: "P55", translation: "SÌ carne Per favore" },
  { id: "P56", translation: "grande manzo caldo Per favore" },
  { id: "P57", translation: "uova con maiale E fagioli Per favore" },
  { id: "P58", translation: "molto bene" },
  { id: "P59", translation: "Mi scusi" },
  { id: "P60", translation: "con pomodori" },
  { id: "P61", translation: "Scusa arrivederci" },
  { id: "P62", translation: "Mio nome È" },
  { id: "P63", translation: "è lì carta igienica?" },
  { id: "P64", translation: "SÌ, Ho bisogno IL bagno" },
  { id: "P65", translation: "prenotazione per due, Per favore" },
  { id: "P66", translation: "per uno, Per favore" },
  { id: "P67", translation: "con sale, Per favore" },
  { id: "P68", translation: "senza funghi, Per favore" },
  { id: "P69", translation: "caffè con latte E uno zucchero" },
  { id: "P70", translation: "Uscita Sinistra" },
  { id: "P71", translation: "Entrata Giusto" },
  { id: "P72", translation: "Primo Giusto" },
  { id: "P73", translation: "secondo Sinistra" },
  { id: "P74", translation: "Primo strada Sinistra" },
  { id: "P75", translation: "secondo strada Giusto" },
  { id: "P76", translation: "Che cosa tempo È IL autobus ritorno?" },
  { id: "P78", translation: "formaggio al mercato" },
  { id: "P79", translation: "Ho bisogno un farmacia" },
  { id: "P80", translation: "forno per pane con formaggio" },
  { id: "P81", translation: "Dove È IL aeroporto?" },
  { id: "P82", translation: "Grazie, arrivederci" },
  { id: "P83", translation: "uno, due, tre" },
  { id: "P84", translation: "cinque, dieci, cinquanta" },
  { id: "P85", translation: "venti, venticinque" },
  { id: "P86", translation: "Che cosa tempo Sei Chiuso?" },
  { id: "P87", translation: "quattro, cinque, sei" },
  { id: "P88", translation: "uno vino" },
  { id: "P89", translation: "Sette, otto, nove" },
  { id: "P90", translation: "undici, dodici" },
  { id: "P91", translation: "metà, trenta" },
  { id: "P92", translation: "quindici, quarantacinque" },
  { id: "P93", translation: "Grazie" },
  { id: "P94", translation: "Ciao" },
  { id: "P95", translation: "menù?" },
  { id: "P96", translation: "buon appetito!" },
  { id: "P97", translation: "due" },
  { id: "P98", translation: "tre" },
  { id: "P99", translation: "dieci" },
  { id: "P100", translation: "cinquanta" },
  { id: "P101", translation: "venti" },
  { id: "P102", translation: "venticinque" },
  { id: "P103", translation: "acqua?" },
  { id: "P104", translation: "aprire" },
  { id: "P105", translation: "uno -- due" },
  { id: "P106", translation: "due -- tre" },
  { id: "P107", translation: "due -- cinque" },
  { id: "P108", translation: "quattro -- sei" },
  { id: "P109", translation: "Chiuso" },
  { id: "P110", translation: "uno -- tre" },
  { id: "P111", translation: "centro" },
  { id: "P112", translation: "autobus" },
  { id: "P113", translation: "Taxi" },
  { id: "P114", translation: "Entrata" },
  { id: "P115", translation: "Uscita" },
  { id: "P116", translation: "quanti bevande?" },
  { id: "P117", translation: "quanti?" },
  { id: "P118", translation: "due con formaggio, tre senza formaggio" },
  { id: "P119", translation: "Prego" },
  { id: "P120", translation: "Voi Bisogno modifica?" },
  { id: "P121", translation: "Quanto?" },
  { id: "P122", translation: "venti nove" },
  { id: "P123", translation: "cinque" },
  { id: "P124", translation: "dodici trenta" },
  { id: "P125", translation: "cinque venticinque" },
  { id: "P126", translation: "sei trenta" },
  { id: "P127", translation: "due trenta" },
  { id: "P128", translation: "quattro quarantacinque" },
  { id: "P129", translation: "tre quindici" },
  { id: "P130", translation: "uno trenta" },
  { id: "P131", translation: "due ora trenta minuto" },
  { id: "P132", translation: "uno ora dieci minuto" },
  { id: "P133", translation: "speziato pollo" },
  { id: "P134", translation: "pollo E formaggio" },
  { id: "P135", translation: "grande bevande" },
  { id: "P136", translation: "piccolo bevande" },
  { id: "P137", translation: "?" },
  { id: "P138", translation: "Scusami" },
  { id: "P139", translation: "Scusa" },
  { id: "P140", translation: "Che cosa tempo?" },
  { id: "P141", translation: "bevande?" },
  { id: "P142", translation: "acqua" },
  { id: "P143", translation: "funghi" },
  { id: "P144", translation: "autobus Sinistra" },
  { id: "P145", translation: "autobus Giusto" },
  { id: "P146", translation: "Dove È IL Hotel?" },
];
