// Data used to generate lessons.

export default lessonData = [
  {
    lessonId: 1,
    title: "Lesson 1",
    style: 1,
    reviewWords: [],
    phrases: [1],
    prompts: [],
  },
  {
    lessonId: 2,
    title: "Lesson 2",
    style: 2,
    reviewWords: ["where", "bathroom"],
    phrases: [3, 2],
    prompts: [],
  },
  {
    lessonId: 3,
    title: "Lesson 3",
    style: 3,
    reviewWords: [],
    phrases: [4],
    prompts: [1],
  },
  {
    lessonId: 4,
    title: "Lesson 4",
    style: 3,
    reviewWords: ["good", "hello", "where"],
    phrases: [82],
    prompts: [2],
  },
  {
    lessonId: 5,
    title: "Lesson 5",
    style: 3,
    reviewWords: ["good", "goodbye", "hello"],
    phrases: [5],
    prompts: [],
  },
  {
    lessonId: 6,
    title: "Lesson 6",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 7,
    title: "Lesson 7",
    style: 2,
    reviewWords: ["please"],
    phrases: [6, 7],
    prompts: [],
  },
  {
    lessonId: 8,
    title: "Lesson 8",
    style: 6,
    reviewWords: ["excuse_me", "bathroom"],
    phrases: [8],
    prompts: [],
  },
  {
    lessonId: 9,
    title: "Lesson 9",
    style: 5,
    reviewWords: ["menu", "water"],
    phrases: [9],
    prompts: [],
  },
  {
    lessonId: 10,
    title: "Lesson 10",
    style: 2,
    reviewWords: ["you"],
    phrases: [10],
    prompts: [],
  },
  {
    lessonId: 11,
    title: "Lesson 11",
    style: 6,
    reviewWords: ["menu", "check"],
    phrases: [11],
    prompts: [],
  },
  {
    lessonId: 12,
    title: "Lesson 12",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 13,
    title: "Lesson 13",
    style: 2,
    reviewWords: [],
    phrases: [12, 83],
    prompts: [6],
  },

  {
    lessonId: 14,
    title: "Lesson 14",
    style: 8,
    reviewWords: ["how_much"],
    phrases: [13, 84],
    prompts: [],
  },
  {
    lessonId: 15,
    title: "Lesson 15",
    style: 2,
    reviewWords: ["how_much", "ten", "fifty"],
    phrases: [14, 85],
    prompts: [],
  },
  {
    lessonId: 16,
    title: "Lesson 16",
    style: 7,
    reviewWords: ["how_much", "this", "cost", "excuse_me", "please"],
    phrases: [15, 16],
    prompts: [],
  },
  {
    lessonId: 17,
    title: "Lesson 17",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 18,
    title: "Lesson 18",
    style: 9,
    reviewWords: ["bathroom", "where"],
    phrases: [97], // [17],
    prompts: [7],
  },
  {
    lessonId: 19,
    title: "Lesson 19",
    style: 6,
    reviewWords: ["open", "closed"],
    phrases: [86],
    prompts: [],
  },
  {
    lessonId: 20,
    title: "Lesson 20",
    style: 8,
    reviewWords: ["yes", "no"],
    phrases: [83],
    prompts: [],
  },
  {
    lessonId: 21,
    title: "Lesson 21",
    style: 2,
    reviewWords: ["what"],
    phrases: [87],
    prompts: [],
  },
  {
    lessonId: 22,
    title: "Lesson 22",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 23,
    title: "Lesson 23",
    style: 6,
    reviewWords: ["where", "is"],
    phrases: [22],
    prompts: [],
  },
  {
    lessonId: 24,
    title: "Lesson 24",
    style: 2,
    reviewWords: ["where", "excuse_me"],
    phrases: [20],
    prompts: [],
  },
  {
    lessonId: 25,
    title: "Lesson 25",
    style: 5,
    reviewWords: ["I_need"],
    phrases: [21],
    prompts: [],
  },
  {
    lessonId: 26,
    title: "Lesson 26",
    style: 3,
    reviewWords: ["bus", "station"],
    phrases: [18, 19],
    prompts: [],
  },
  {
    lessonId: 27,
    title: "Lesson 27",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 28,
    title: "Lesson 28",
    style: 2,
    reviewWords: ["with", "without"],
    phrases: [23, 24],
    prompts: [],
  },
  {
    lessonId: 29,
    title: "Lesson 29",
    style: 4,
    reviewWords: ["chicken", "cheese", "one", "two"],
    phrases: [25, 26],
    prompts: [],
  },
  {
    lessonId: 30,
    title: "Lesson 30",
    style: 6,
    reviewWords: ["large", "water", "three"],
    phrases: [27],
    prompts: [],
  },
  {
    lessonId: 31,
    title: "Lesson 31",
    style: 8,
    reviewWords: ["please"],
    phrases: [28, 88],
    prompts: [],
  },
  {
    lessonId: 32,
    title: "Lesson 32",
    style: 6,
    reviewWords: [],
    phrases: [29, 31],
    prompts: [],
  },
  {
    lessonId: 33,
    title: "Lesson 33",
    style: 7,
    reviewWords: ["cheese"],
    phrases: [30],
    prompts: [],
  },
  {
    lessonId: 34,
    title: "Lesson 34",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 35,
    title: "Lesson 35",
    style: 2,
    reviewWords: ["you"],
    phrases: [32],
    prompts: [],
  },
  {
    lessonId: 36,
    title: "Lesson 36",
    style: 2,
    reviewWords: ["thank_you", "yes"],
    phrases: [33],
    prompts: [],
  },
  {
    lessonId: 38,
    title: "Lesson 38",
    style: 2,
    reviewWords: ["speak", "hello"],
    phrases: [34, 35],
    prompts: [],
  },
  {
    lessonId: 39,
    title: "Lesson 39",
    style: 8,
    reviewWords: ["how_are_you"],
    phrases: [37, 36],
    prompts: [],
  },
  {
    lessonId: 40,
    title: "Lesson 40",
    style: 8,
    reviewWords: ["goodbye", "and"],
    phrases: [38],
    prompts: [],
  },
  {
    lessonId: 41,
    title: "Lesson 41",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 42,
    title: "Lesson 42",
    style: 2,
    reviewWords: ["please", "how_much"],
    phrases: [39, 40],
    prompts: [],
  },
  {
    lessonId: 43,
    title: "Lesson 43",
    style: 4,
    reviewWords: ["cost", "one", "two", "three"],
    phrases: [41],
    prompts: [],
  },
  {
    lessonId: 44,
    title: "Lesson 44",
    style: 5,
    reviewWords: ["fifty", "ten", "five"],
    phrases: [42],
    prompts: [],
  },
  {
    lessonId: 45,
    title: "Lesson 45",
    style: 5,
    reviewWords: ["four", "five", "six"],
    phrases: [89],
    prompts: [],
  },
  {
    lessonId: 46,
    title: "Lesson 46",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 47,
    title: "Lesson 47",
    style: 2,
    reviewWords: ["what", "one", "two", "three"],
    phrases: [43],
    prompts: [],
  },
  {
    lessonId: 48,
    title: "Lesson 48",
    style: 8,
    reviewWords: ["time", "what", "four", "five", "six"],
    phrases: [90, 91],
    prompts: [],
  },
  {
    lessonId: 49,
    title: "Lesson 49",
    style: 6,
    reviewWords: ["open", "closed"],
    phrases: [44, 47],
    prompts: [],
  },
  {
    lessonId: 50,
    title: "Lesson 50",
    style: 4,
    reviewWords: ["seven", "eight", "nine", "ten"],
    phrases: [93],
    prompts: [],
  },
  {
    lessonId: 51,
    title: "Lesson 51",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 52,
    title: "Lesson 52",
    style: 2,
    reviewWords: ["how_much"],
    phrases: [45],
    prompts: [],
  },
  {
    lessonId: 53,
    title: "Lesson 53",
    style: 3,
    reviewWords: ["two", "entrance", "station"],
    phrases: [46],
    prompts: [],
  },
  {
    lessonId: 54,
    title: "Lesson 54",
    style: 7,
    reviewWords: ["what", "time", "exit"],
    phrases: [48],
    prompts: [],
  },
  {
    lessonId: 55,
    title: "Lesson 55",
    style: 8,
    reviewWords: ["twenty"],
    phrases: [49],
    prompts: [],
  },
  {
    lessonId: 56,
    title: "Lesson 56",
    style: 3,
    reviewWords: ["train"],
    phrases: [50],
    prompts: [],
  },
  {
    lessonId: 57,
    title: "Lesson 57",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 58,
    title: "Lesson 58",
    style: 3,
    reviewWords: ["cheese", "chicken"],
    phrases: [51, 52],
    prompts: [],
  },
  {
    lessonId: 59,
    title: "Lesson 59",
    style: 2,
    reviewWords: [],
    phrases: [53],
    prompts: [],
  },
  {
    lessonId: 60,
    title: "Lesson 60",
    style: 5,
    reviewWords: ["yes", "please"],
    phrases: [54, 55],
    prompts: [],
  },
  {
    lessonId: 61,
    title: "Lesson 61",
    style: 6,
    reviewWords: ["large", "beef"],
    phrases: [56],
    prompts: [],
  },
  {
    lessonId: 62,
    title: "Lesson 62",
    style: 6,
    reviewWords: ["pork", "and"],
    phrases: [57],
    prompts: [],
  },
  {
    lessonId: 63,
    title: "Lesson 63",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 64,
    title: "Lesson 64",
    style: 8,
    reviewWords: ["good", "how_are_you"],
    phrases: [58],
    prompts: [],
  },
  {
    lessonId: 65,
    title: "Lesson 65",
    style: 8,
    reviewWords: ["hello", "goodbye"],
    phrases: [59],
    prompts: [],
  },
  {
    lessonId: 66,
    title: "Lesson 66",
    style: 5,
    reviewWords: [],
    phrases: [61],
    prompts: [],
  },
  {
    lessonId: 67,
    title: "Lesson 67",
    style: 2,
    reviewWords: ["is"],
    phrases: [62],
    prompts: [],
  },
  {
    lessonId: 68,
    title: "Lesson 68",
    style: 5,
    reviewWords: ["bathroom", "where", "I_need"],
    phrases: [63, 64],
    prompts: [],
  },
  {
    lessonId: 69,
    title: "Lesson 69",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 70,
    title: "Lesson 70",
    style: 2,
    reviewWords: ["for", "one", "two", "three"],
    phrases: [65, 66],
    prompts: [],
  },
  {
    lessonId: 71,
    title: "Lesson 71",
    style: 6,
    reviewWords: ["with", "please"],
    phrases: [67],
    prompts: [],
  },
  {
    lessonId: 72,
    title: "Lesson 72",
    style: 6,
    reviewWords: ["without", "bread", "salt"],
    phrases: [68, 60],
    prompts: [],
  },
  {
    lessonId: 73,
    title: "Lesson 73",
    style: 5,
    reviewWords: ["coffee", "water"],
    phrases: [69],
    prompts: [],
  },
  {
    lessonId: 74,
    title: "Lesson 74",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 75,
    title: "Lesson 75",
    style: 6,
    reviewWords: ["entrance", "exit"],
    phrases: [70, 71],
    prompts: [],
  },
  {
    lessonId: 76,
    title: "Lesson 76",
    style: 8,
    reviewWords: ["left", "right"],
    phrases: [72, 73],
    prompts: [],
  },
  {
    lessonId: 77,
    title: "Lesson 77",
    style: 2,
    reviewWords: ["first", "second"],
    phrases: [74, 75],
    prompts: [],
  },
  {
    lessonId: 78,
    title: "Lesson 78",
    style: 2,
    reviewWords: ["bus", "what", "time"],
    phrases: [76],
    prompts: [],
  },
  {
    lessonId: 79,
    title: "Lesson 79",
    style: 5,
    reviewWords: ["all", "trains"],
    phrases: [77],
    prompts: [],
  },
  {
    lessonId: 80,
    title: "Lesson 80",
    style: 10,
    reviewWords: ["entrance", "exit"],
    phrases: [],
    prompts: [],
  },
  {
    lessonId: 81,
    title: "Lesson 81",
    style: 2,
    reviewWords: ["where", "is"],
    phrases: [78],
    prompts: [],
  },
  {
    lessonId: 82,
    title: "Lesson 82",
    style: 2,
    reviewWords: ["I need"],
    phrases: [79],
    prompts: [],
  },
  {
    lessonId: 83,
    title: "Lesson 83",
    style: 7,
    reviewWords: ["bread", "with", "cheese"],
    phrases: [80],
    prompts: [],
  },
  {
    lessonId: 84,
    title: "Lesson 84",
    style: 2,
    reviewWords: ["street", "left", "right"],
    phrases: [81],
    prompts: [],
  },
  {
    lessonId: 85,
    title: "Lesson 85",
    style: 10,
    reviewWords: [],
    phrases: [],
    prompts: [],
  },
];
