// Prompts

export default prompts = [
  {
    promptId: 1,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond?",
    phrase: 2,
    phrase2: null,
    icon: [],
    choices: [15, 4],
    correctChoice: [4],
  },
  {
    promptId: 2,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond?",
    phrase: 3,
    phrase2: null,
    icon: [],
    choices: [2, 4],
    correctChoice: [2],
  },
  {
    promptId: 3,
    screenType: "prompt",
    screenSubType: "chat",
    instruction:
      "How would you respond if someone hands you something you dropped?",
    phrase: 94,
    phrase2: null,
    icon: [],
    choices: [93, 4],
    correctChoice: [93],
  },
  {
    promptId: 4,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond?",
    phrase: 95,
    phrase2: null,
    icon: [],
    choices: [93, 94, 2],
    correctChoice: [93],
  },
  {
    promptId: 5,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond?",
    phrase: 96,
    phrase2: null,
    icon: [],
    choices: [3, 93, 94],
    correctChoice: [93],
  },
  {
    promptId: 6,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How much does it cost?",
    phrase: 12,
    phrase2: 97,
    icon: [],
    choices: [97, 98],
    correctChoice: [97],
  },
  {
    promptId: 7,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How much does it cost?",
    phrase: 13,
    phrase2: 99,
    icon: [],
    choices: [99, 100, 97],
    correctChoice: [99],
  },
  {
    promptId: 8,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How much does it cost?",
    phrase: 12,
    phrase2: 101,
    icon: [],
    choices: [101, 99, 102],
    correctChoice: [101],
  },
  {
    promptId: 9,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What would you say if you want the menu?",
    phrase: 95,
    phrase2: null,
    icon: [],
    choices: [15, 16, 7],
    correctChoice: [15],
  },
  {
    promptId: 10,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What would you say if you don't want water?",
    phrase: 103,
    phrase2: null,
    icon: [],
    choices: [15, 16, 7],
    correctChoice: [16],
  },
  {
    promptId: 11,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What time is this place open?",
    phrase: 104,
    phrase2: "1 - 2",
    icon: [],
    choices: [105, 106],
    correctChoice: [105],
  },
  {
    promptId: 13,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What time is this place open?",
    phrase: 104,
    phrase2: "2 - 5",
    icon: [],
    choices: [107, 108],
    correctChoice: [107],
  },
  {
    promptId: 12,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What time is this place closed?",
    phrase: 109,
    phrase2: "1 - 3",
    icon: [],
    choices: [110, 105],
    correctChoice: [110],
  },
  {
    promptId: 14,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What time is this place closed?",
    phrase: 109,
    phrase2: "2 - 3",
    icon: [],
    choices: [106, 105],
    correctChoice: [106],
  },
  {
    promptId: 15,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 111,
    phrase2: null,
    icon: ["target", "Feather"],
    choices: [111, 112],
    correctChoice: [111],
  },
  {
    promptId: 16,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 113,
    phrase2: null,
    icon: ["taxi", "FontAwesome5"],
    choices: [111, 113],
    correctChoice: [113],
  },
  {
    promptId: 17,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 112,
    phrase2: null,
    icon: ["bus", "FontAwesome5"],
    choices: [112, 113],
    correctChoice: [112],
  },
  {
    promptId: 18,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 114,
    phrase2: null,
    icon: ["enter-outline", "Ionicons"],
    choices: [114, 115],
    correctChoice: [114],
  },
  {
    promptId: 19,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 115,
    phrase2: null,
    icon: ["exit-outline", "Ionicons"],
    choices: [115, 114],
    correctChoice: [115],
  },
  {
    promptId: 20,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How many did you just order?",
    phrase: 117,
    phrase2: 99,
    icon: [],
    choices: [99, 101, 97],
    correctChoice: [99],
  },
  {
    promptId: 21,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How many did you just order with cheese?",
    phrase: 117,
    phrase2: 97,
    icon: [],
    choices: [97, 98, 101],
    correctChoice: [97],
  },
  {
    promptId: 22,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond?",
    phrase: 93,
    phrase2: null,
    icon: [],
    choices: [119, 15, 94],
    correctChoice: [119],
  },
  {
    promptId: 23,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond that you do?",
    phrase: 120,
    phrase2: null,
    icon: [],
    choices: [15, 16],
    correctChoice: [15],
  },
  {
    promptId: 24,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How much does it cost?",
    phrase: 121,
    phrase2: 100,
    icon: [],
    choices: [100, 101, 102],
    correctChoice: [100],
  },
  {
    promptId: 25,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How much does it cost?",
    phrase: 121,
    phrase2: 122,
    icon: [],
    choices: [122, 99, 101],
    correctChoice: [100],
  },
  {
    promptId: 26,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What time is it?",
    phrase: 43,
    phrase2: 123,
    icon: [],
    choices: [123, 97, 99],
    correctChoice: [123],
  },
  {
    promptId: 27,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What time is it?",
    phrase: 43,
    phrase2: 124,
    icon: [],
    choices: [124, 125],
    correctChoice: [123],
  },
  {
    promptId: 28,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What time is this place open?",
    phrase: 104,
    phrase2: "1899-12-30T11:30:00.000Z",
    icon: [],
    choices: [126, 127],
    correctChoice: [126],
  },
  {
    promptId: 29,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What time is this place closed?",
    phrase: 109,
    phrase2: "1899-12-30T06:30:00.000Z",
    icon: [],
    choices: [130, 127],
    correctChoice: [130],
  },
  {
    promptId: 30,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What time is it?",
    phrase: 43,
    phrase2: 128,
    icon: [],
    choices: [128, 129],
    correctChoice: [128],
  },
  {
    promptId: 31,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What time is it at?",
    phrase: 48,
    phrase2: 98,
    icon: [],
    choices: [98, 97, 123],
    correctChoice: [98],
  },
  {
    promptId: 32,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How much time does it take?",
    phrase: 45,
    phrase2: 131,
    icon: [],
    choices: [131, 132],
    correctChoice: [131],
  },
  {
    promptId: 33,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What is this menu item?",
    phrase: 133,
    phrase2: null,
    icon: [],
    choices: [133, 134],
    correctChoice: [133],
  },
  {
    promptId: 34,
    screenType: "prompt",
    screenSubType: "sign",
    instruction: "What is this menu item?",
    phrase: 135,
    phrase2: null,
    icon: [],
    choices: [135, 136],
    correctChoice: [135],
  },
  {
    promptId: 35,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "Which would you use to get someone's attention?",
    phrase: 137,
    phrase2: null,
    icon: [],
    choices: [138, 59],
    correctChoice: [138],
  },
  {
    promptId: 36,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "Which would you use to pass by someone on a bus?",
    phrase: 137,
    phrase2: null,
    icon: [],
    choices: [59, 138],
    correctChoice: [59],
  },
  {
    promptId: 37,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How would you respond?",
    phrase: 2,
    phrase2: null,
    icon: [],
    choices: [58, 38],
    correctChoice: [58],
  },
  {
    promptId: 38,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "Which would you use to offer an apology?",
    phrase: 137,
    phrase2: null,
    icon: [],
    choices: [139, 59, 138],
    correctChoice: [139],
  },
  {
    promptId: 39,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "What might you be asked if scheduling a reservation?",
    phrase: 65,
    phrase2: null,
    icon: [],
    choices: [140, 116],
    correctChoice: [140],
  },
  {
    promptId: 40,
    screenType: "prompt",
    screenSubType: "chat",
    instruction: "How could you respond?",
    phrase: 141,
    phrase2: null,
    icon: [],
    choices: [142, 143],
    correctChoice: [142],
  },
  {
    promptId: 41,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 112,
    phrase2: null,
    icon: ["arrow-left-top", "MaterialCommunityIcons"],
    choices: [144, 145],
    correctChoice: [144],
  },
  {
    promptId: 42,
    screenType: "prompt",
    screenSubType: "icon",
    instruction: "What is this a sign for?",
    phrase: 112,
    phrase2: null,
    icon: ["arrow-right-top", "MaterialCommunityIcons"],
    choices: [145, 144],
    correctChoice: [145],
  },
];
